#ifndef WEIGHTS_H_INCLUDED
#define WEIGHTS_H_INCLUDED

extern const short _binary_weights_nnue_perspective_b0_short_32_bin_start[];
extern const short _binary_weights_nnue_perspective_w0_short_45056_32_bin_start[];
extern const int _binary_weights_nnue_stacks_b0_int_4_bin_start[];
extern const char _binary_weights_nnue_stacks_w0_char_4_64_bin_start[];
extern const float _binary_weights_time_block_in_b_float_24_bin_start[];
extern const float _binary_weights_time_block_in_w_float_24_24_3_3_bin_start[];
extern const float _binary_weights_time_block_out_b_float_24_bin_start[];
extern const float _binary_weights_time_block_out_w_float_24_24_3_3_bin_start[];
extern const float _binary_weights_time_head_b_float_1_bin_start[];
extern const float _binary_weights_time_head_b_float_64_bin_start[];
extern const float _binary_weights_time_head_w_float_1_64_bin_start[];
extern const float _binary_weights_time_head_w_float_64_100_bin_start[];
extern const float _binary_weights_time_initial_b_float_24_bin_start[];
extern const float _binary_weights_time_initial_w_float_24_14_3_3_bin_start[];

#endif // WEIGHTS_H_INCLUDED
