name: "Linting Checks"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_pr:
    name: "Source Code"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Linter
        uses: super-linter/super-linter@v8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MULTI_STATUS: false
          VALIDATE_CLANG_FORMAT: true
          VALIDATE_PYTHON_BLACK: true
          LINTER_RULES_PATH: .
          CLANG_FORMAT_FILE_NAME: .clang-format
          FILTER_REGEX_EXCLUDE: include/weights.h
