name: "Build Executable"

on:
  push:
    branches:
      - "master"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and test executable on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        include:
          - os: windows-latest
            target: Windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Compile program with cmake
        run: |
          mkdir build
          cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target Pingu --config Release --

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest"
          files: "build/Pingu.exe"
