name: "Test PR"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  engine_tests:
    name: Engine Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build executable
        run: make

      - name: Navigate to tests folder
        run: cd testing

      - name: Perft test
        run: python3 perft_check.py

      - name: Incremental update test
        run: python3 incremental_check.py

      - name: Move validation test
        run: python3 move_validation_check.py

      - name: Fen test
        run: python3 fen_check.py

      - name: SEE test
        run: python3 see_check.py
