name: "Validate PR Details"

on:
  pull_request:
    types: [opened, edited]

jobs:
  validate_pr_details:
    name: Title
    runs-on: ubuntu-latest
    steps:
      - name: Semantic name check
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: PIN-\d+
          requireScope: true
          subjectPattern: ^(?![A-Z]).+$
